// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// ClubSync Firebase configuration - Now uses team-sync-soccer project (shared with TeamSync)
/// ClubSync and TeamSync use the same Firebase project but different data structures
///
/// Example:
/// ```dart
/// import 'firebase_options_club.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptionsClub.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsClub {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'ClubSync is not supported on macOS. Use web or mobile platforms.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptionsClub have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsClub have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsClub are not supported for this platform.',
        );
    }
  }

  // Helper to read an env var (required). Throws if missing to avoid embedding secret fallbacks.
  static String _env(String key) {
    final v = dotenv.env[key];
    if (v != null && v.trim().isNotEmpty) return v.trim();
    throw StateError(
        'Missing required environment variable: $key. Provide it in .env or CI secrets.');
  }

  // Web configuration for ClubSync (uses compile-time environment variables)
  static FirebaseOptions get web => FirebaseOptions(
        apiKey: const String.fromEnvironment('WEB_API_KEY', defaultValue: ''),
        appId: const String.fromEnvironment('CLUBSYNC_WEB_APP_ID',
            defaultValue: ''),
        messagingSenderId: const String.fromEnvironment('MESSAGING_SENDER_ID',
            defaultValue: ''),
        projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID',
            defaultValue: ''),
        authDomain: const String.fromEnvironment('CLUBSYNC_WEB_AUTH_DOMAIN',
            defaultValue: ''),
        databaseURL: const String.fromEnvironment('FIREBASE_DATABASE_URL',
            defaultValue: ''),
        storageBucket: const String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
            defaultValue: ''),
        measurementId: const String.fromEnvironment(
            'CLUBSYNC_WEB_MEASUREMENT_ID',
            defaultValue: ''),
      );

  // Android configuration for ClubSync
  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _env('CLUBSYNC_ANDROID_API_KEY'),
        appId: _env('CLUBSYNC_ANDROID_APP_ID'),
        messagingSenderId: _env('MESSAGING_SENDER_ID'),
        projectId: _env('FIREBASE_PROJECT_ID'),
        databaseURL: _env('FIREBASE_DATABASE_URL'),
        storageBucket: _env('FIREBASE_STORAGE_BUCKET'),
      );

  // iOS configuration for ClubSync
  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _env('CLUBSYNC_IOS_API_KEY'),
        appId: _env('CLUBSYNC_IOS_APP_ID'),
        messagingSenderId: _env('MESSAGING_SENDER_ID'),
        projectId: _env('FIREBASE_PROJECT_ID'),
        databaseURL: _env('FIREBASE_DATABASE_URL'),
        storageBucket: _env('FIREBASE_STORAGE_BUCKET'),
        iosClientId: _env('CLUBSYNC_IOS_CLIENT_ID'),
        iosBundleId: _env('CLUBSYNC_IOS_BUNDLE_ID'),
      );
}
