// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBflWvgLKjvXjmRAYw0HpQyLfSXbhm2sEg',
    appId: '1:542457934179:android:fc3f9989d51f9e2cc52356',
    messagingSenderId: '542457934179',
    projectId: 'team-sync-soccer',
    databaseURL: 'https://team-sync-soccer-default-rtdb.firebaseio.com',
    storageBucket: 'team-sync-soccer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtiLAs5regSXQXpvx-zcihvMuAeK89Beo',
    appId: '1:542457934179:ios:61b944505cc95e7bc52356',
    messagingSenderId: '542457934179',
    projectId: 'team-sync-soccer',
    databaseURL: 'https://team-sync-soccer-default-rtdb.firebaseio.com',
    storageBucket: 'team-sync-soccer.firebasestorage.app',
    androidClientId: '542457934179-7l4c1l8galtjfi36vob54gj1rp7q2530.apps.googleusercontent.com',
    iosClientId: '542457934179-huq726t2agepvcaa7fq2do3abob3eb1j.apps.googleusercontent.com',
    iosBundleId: 'com.tsquared.teamsync.soccer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZVVLJIaWnHSF3rZ9JXgUtaq0fVE2s-Cs',
    appId: '1:542457934179:web:991c3eb3d8c445bbc52356',
    messagingSenderId: '542457934179',
    projectId: 'team-sync-soccer',
    authDomain: 'team-sync-soccer.firebaseapp.com',
    databaseURL: 'https://team-sync-soccer-default-rtdb.firebaseio.com',
    storageBucket: 'team-sync-soccer.firebasestorage.app',
    measurementId: 'G-Y5Y26V84T8',
  );

}